@echo off
setlocal enabledelayedexpansion

:: ===================================================================
:: Firefox Cookie Blocking Script
:: Configures Mozilla Firefox to block cookies and tracking
:: ===================================================================

echo   - Configuring Mozilla Firefox...

:: Firefox profile directories
set "FIREFOX_PROFILES=%APPDATA%\Mozilla\Firefox\Profiles"
set "FIREFOX_INSTALL=%PROGRAMFILES%\Mozilla Firefox"
set "FIREFOX_INSTALL_X86=%PROGRAMFILES(X86)%\Mozilla Firefox"

:: Check if Firefox is installed
if not exist "%FIREFOX_PROFILES%" (
    if not exist "%FIREFOX_INSTALL%" (
        if not exist "%FIREFOX_INSTALL_X86%" (
            echo     Firefox not found - skipping Firefox configuration
            exit /b 0
        )
    )
)

:: Kill Firefox processes if running
taskkill /f /im firefox.exe >nul 2>&1

:: Find Firefox profiles
if not exist "%FIREFOX_PROFILES%" (
    echo     Firefox profiles directory not found - creating default profile structure
    mkdir "%APPDATA%\Mozilla\Firefox\Profiles" 2>nul
    mkdir "%APPDATA%\Mozilla\Firefox\Profiles\default.default" 2>nul
    set "PROFILE_DIR=%APPDATA%\Mozilla\Firefox\Profiles\default.default"
) else (
    :: Find the default profile
    set "PROFILE_DIR="
    for /d %%i in ("%FIREFOX_PROFILES%\*.default*") do (
        set "PROFILE_DIR=%%i"
        goto :found_profile
    )
    
    :: If no default profile found, use the first available profile
    for /d %%i in ("%FIREFOX_PROFILES%\*") do (
        set "PROFILE_DIR=%%i"
        goto :found_profile
    )
    
    :: If no profiles found, create one
    if "!PROFILE_DIR!"=="" (
        mkdir "%FIREFOX_PROFILES%\default.default" 2>nul
        set "PROFILE_DIR=%FIREFOX_PROFILES%\default.default"
    )
)

:found_profile
if "%PROFILE_DIR%"=="" (
    echo     Error: Could not determine Firefox profile directory
    exit /b 1
)

echo     Using Firefox profile: %PROFILE_DIR%

:: Create user.js for cookie blocking configuration
echo     Creating Firefox user.js configuration...

set "USER_JS=%PROFILE_DIR%\user.js"

:: Backup existing user.js if present
if exist "%USER_JS%" (
    copy "%USER_JS%" "%USER_JS%.backup" >nul 2>&1
)

:: Create comprehensive Firefox privacy configuration
(
echo // Firefox Cookie Blocking and Privacy Configuration
echo // Generated by Cookie Blocking Solution
echo.
echo // === COOKIE SETTINGS ===
echo // Block all cookies by default
echo user_pref("network.cookie.cookieBehavior", 2^);
echo // Block third-party cookies
echo user_pref("network.cookie.thirdparty.sessionOnly", true^);
echo user_pref("network.cookie.thirdparty.nonsecureSessionOnly", true^);
echo // Disable cookie lifetime policy
echo user_pref("network.cookie.lifetimePolicy", 2^);
echo // Block tracking cookies
echo user_pref("privacy.trackingprotection.enabled", true^);
echo user_pref("privacy.trackingprotection.pbmode.enabled", true^);
echo user_pref("privacy.trackingprotection.cryptomining.enabled", true^);
echo user_pref("privacy.trackingprotection.fingerprinting.enabled", true^);
echo user_pref("privacy.trackingprotection.socialtracking.enabled", true^);
echo.
echo // === ENHANCED TRACKING PROTECTION ===
echo user_pref("browser.contentblocking.category", "strict"^);
echo user_pref("privacy.annotate_channels.strict_list.enabled", true^);
echo user_pref("privacy.partition.network_state", true^);
echo user_pref("privacy.dynamic_firstparty.use_site", true^);
echo.
echo // === DISABLE TELEMETRY ===
echo user_pref("toolkit.telemetry.enabled", false^);
echo user_pref("toolkit.telemetry.unified", false^);
echo user_pref("toolkit.telemetry.archive.enabled", false^);
echo user_pref("datareporting.healthreport.uploadEnabled", false^);
echo user_pref("datareporting.policy.dataSubmissionEnabled", false^);
echo user_pref("app.shield.optoutstudies.enabled", false^);
echo user_pref("browser.discovery.enabled", false^);
echo user_pref("browser.crashReports.unsubmittedCheck.autoSubmit2", false^);
echo.
echo // === DISABLE PREFETCHING ===
echo user_pref("network.dns.disablePrefetch", true^);
echo user_pref("network.prefetch-next", false^);
echo user_pref("network.predictor.enabled", false^);
echo user_pref("network.predictor.enable-prefetch", false^);
echo user_pref("network.http.speculative-parallel-limit", 0^);
echo.
echo // === DISABLE GEOLOCATION ===
echo user_pref("geo.enabled", false^);
echo user_pref("geo.provider.network.url", ""^);
echo user_pref("browser.region.network.url", ""^);
echo user_pref("browser.region.update.enabled", false^);
echo.
echo // === DISABLE NOTIFICATIONS ===
echo user_pref("dom.webnotifications.enabled", false^);
echo user_pref("dom.push.enabled", false^);
echo user_pref("dom.push.connection.enabled", false^);
echo.
echo // === DISABLE AUTOPLAY ===
echo user_pref("media.autoplay.default", 5^);
echo user_pref("media.autoplay.blocking_policy", 2^);
echo.
echo // === DISABLE POCKET ===
echo user_pref("extensions.pocket.enabled", false^);
echo user_pref("extensions.pocket.api", ""^);
echo user_pref("extensions.pocket.oAuthConsumerKey", ""^);
echo user_pref("extensions.pocket.site", ""^);
echo.
echo // === DISABLE EXPERIMENTS ===
echo user_pref("experiments.enabled", false^);
echo user_pref("experiments.manifest.uri", ""^);
echo user_pref("experiments.supported", false^);
echo user_pref("network.allow-experiments", false^);
echo.
echo // === DISABLE FIREFOX SYNC ===
echo user_pref("services.sync.engine.prefs", false^);
echo user_pref("services.sync.engine.passwords", false^);
echo user_pref("services.sync.engine.bookmarks", false^);
echo user_pref("services.sync.engine.history", false^);
echo.
echo // === DISABLE FORM AUTOFILL ===
echo user_pref("extensions.formautofill.addresses.enabled", false^);
echo user_pref("extensions.formautofill.creditCards.enabled", false^);
echo user_pref("signon.rememberSignons", false^);
echo.
echo // === DISABLE CAPTIVE PORTAL ===
echo user_pref("captivedetect.canonicalURL", ""^);
echo user_pref("network.captive-portal-service.enabled", false^);
echo.
echo // === DISABLE SAFE BROWSING DATA COLLECTION ===
echo user_pref("browser.safebrowsing.downloads.remote.enabled", false^);
echo user_pref("browser.safebrowsing.downloads.remote.url", ""^);
echo.
echo // === MIXED CONTENT BLOCKING ===
echo user_pref("security.mixed_content.block_active_content", true^);
echo user_pref("security.mixed_content.block_display_content", true^);
echo.
echo // === WEBRTC PRIVACY ===
echo user_pref("media.peerconnection.enabled", false^);
echo user_pref("media.peerconnection.ice.default_address_only", true^);
echo user_pref("media.peerconnection.ice.no_host", true^);
echo.
echo // === DISABLE MOZILLA VPN PROMOTION ===
echo user_pref("browser.vpn_promo.enabled", false^);
echo.
echo // === RESIST FINGERPRINTING ===
echo user_pref("privacy.resistFingerprinting", true^);
echo user_pref("privacy.resistFingerprinting.letterboxing", true^);
echo.
echo // Configuration completed: %date% %time%
) > "%USER_JS%"

:: Registry settings for Firefox (system-wide policies)
echo     Applying Firefox registry settings...

:: Firefox policies registry keys
reg add "HKLM\SOFTWARE\Policies\Mozilla\Firefox" /v "DisableTelemetry" /t REG_DWORD /d 1 /f >nul 2>&1
reg add "HKLM\SOFTWARE\Policies\Mozilla\Firefox" /v "DisableFirefoxStudies" /t REG_DWORD /d 1 /f >nul 2>&1
reg add "HKLM\SOFTWARE\Policies\Mozilla\Firefox" /v "DisablePocket" /t REG_DWORD /d 1 /f >nul 2>&1
reg add "HKLM\SOFTWARE\Policies\Mozilla\Firefox" /v "DisableFirefoxAccounts" /t REG_DWORD /d 1 /f >nul 2>&1
reg add "HKLM\SOFTWARE\Policies\Mozilla\Firefox" /v "DisableProfileImport" /t REG_DWORD /d 1 /f >nul 2>&1
reg add "HKLM\SOFTWARE\Policies\Mozilla\Firefox" /v "BlockAboutConfig" /t REG_DWORD /d 0 /f >nul 2>&1

:: Create policies.json for additional configuration
set "FIREFOX_DIR=%PROGRAMFILES%\Mozilla Firefox"
if not exist "%FIREFOX_DIR%" set "FIREFOX_DIR=%PROGRAMFILES(X86)%\Mozilla Firefox"

if exist "%FIREFOX_DIR%" (
    if not exist "%FIREFOX_DIR%\distribution" mkdir "%FIREFOX_DIR%\distribution" 2>nul
    
    (
    echo {
    echo   "policies": {
    echo     "Cookies": {
    echo       "Default": false,
    echo       "AcceptThirdParty": "never",
    echo       "Locked": true
    echo     },
    echo     "DisableTelemetry": true,
    echo     "DisableFirefoxStudies": true,
    echo     "DisablePocket": true,
    echo     "DontCheckDefaultBrowser": true,
    echo     "DisableSetDesktopBackground": true,
    echo     "DisableFirefoxAccounts": true,
    echo     "OfferToSaveLogins": false,
    echo     "PasswordManagerEnabled": false,
    echo     "PopupBlocking": {
    echo       "Default": true,
    echo       "Locked": true
    echo     },
    echo     "Preferences": {
    echo       "network.cookie.cookieBehavior": {
    echo         "Value": 2,
    echo         "Status": "locked"
    echo       },
    echo       "privacy.trackingprotection.enabled": {
    echo         "Value": true,
    echo         "Status": "locked"
    echo       }
    echo     }
    echo   }
    echo }
    ) > "%FIREFOX_DIR%\distribution\policies.json"
)

echo     Firefox configuration completed successfully.

exit /b 0